### ISSUE TITLE
Option to specify padding and dilation in RevBlock

### ISSUE THREAD

**Issue by christopher-beckham** [tbung/revnet#5]
Hi,

Thank you for your implementation on it, it seems really interesting!

I tried to take a crack at modifying this code for some of my own work but ended up getting an error along the lines of `RuntimeError: function RevBlockFunctionBackward returned an incorrect number of gradients (expected 33, got 32`. Would it be a (presumably not too hard) feature request to have padding+dilation options added into the RevBlock? It would be greatly appreciated.

Kind regards,
Chris

**Comment by tbung** [comment]
Hi Chris,

I hope this works for you. Right now only the first convolution in the residual function uses the dilation and padding, since this is where stride is applied too. If you want to change this you have to additionally change `size_after_residual` to match. You can also hit me up and I'll change it in the repo.

Checks are implemented for downsampling, since the blocks are only reversible when padding and dilation cancel out.

I did not have time yet, to intensly test the changes, just some quick training to make sure it still runs, so if you notice any bugs open another issue, please. :sweat_smile: 

Kind regards
Till
